const invitedGuests = [
  {
    name:'Haley',
    lastName: 'Young',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'stickz',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Teresa',
    lastName: 'Young',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pumpkin',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Ralph',
    lastName: 'Young',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pumpkin',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Hunter',
    lastName: 'Young',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pranksonmom',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Hailey',
    lastName: 'Young',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pranksonmom',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Erwin',
    lastName: 'White',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'thelegend',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Sharon',
    lastName: 'Davenport',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'hummingbird',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Alex',
    lastName: 'Andrews',
    isFamily: false,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'sneeze!where?',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Garrison',
    lastName: 'Rios',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'haleydoesntknow',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Anne',
    lastName: 'Harjer',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'sassycooper',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Gary',
    lastName: 'Sexton',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'sassycooper',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Barb',
    lastName: 'Sprofera',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Barbara',
    lastName: 'Sprofera',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Danny',
    lastName: 'Rios',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Daniel',
    lastName: 'Rios',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Katelyn',
    lastName: 'Sprofera',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'bananaslug',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Meggie',
    lastName: 'Rios',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'chomo',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Meaghan',
    lastName: 'Rios',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'chomo',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Justin',
    lastName: 'Wilson',
    isFamily: false,
    isWeddingParty: true,
    isDriving: true,
    isFlying: false,
    password: 'beanbagflute',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Mallory',
    lastName: 'Wilson',
    isFamily: false,
    isWeddingParty: true,
    isDriving: true,
    isFlying: false,
    password: 'beanbagflute',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Monic',
    lastName: 'Tando',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Joel',
    lastName: 'Eslinger',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Katy',
    lastName: 'Hawkins',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Jamie',
    lastName: 'Hawkins',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Kevin',
    lastName: 'Wake',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Courtney',
    lastName: 'Peterson',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Courtney',
    lastName: 'Wake',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Cory',
    lastName: 'Henry',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Lydia',
    lastName: 'Bumpous',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Emma',
    lastName: 'Barbian',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Israel',
    lastName: 'Davila',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Sandra',
    lastName: 'Davila',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Garrett',
    lastName: 'Trummer',
    isFamily: false,
    isWeddingParty: false,
    isDriving: false,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Susanna',
    lastName: 'Shivers',
    isFamily: false,
    isWeddingParty: false,
    isDriving: false,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Nicole',
    lastName: 'Ryan',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Leif',
    lastName: 'Ryan',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
];

export function findInvitedGuest(name, lastName) {
  return invitedGuests.find((guest) => {
    return guest.name.toLowerCase() === name.toLowerCase() && guest.lastName.toLowerCase() === lastName?.toLowerCase();
  });
}

export function storeUser(firstName, lastName) {
  const user = findInvitedGuest(firstName, lastName) || {
    name: firstName,
    lastName,
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    isUnrecognizedUser: true,
  };
  localStorage.setItem('user', user.name);
  localStorage.setItem('userLastName', user.lastName);
  return user;
}

export function removeUser() {
  localStorage.removeItem('user');
  localStorage.removeItem('userLastName');
}

export default function useUser() {
  const username = localStorage.getItem('user');
  const lastName = localStorage.getItem('userLastName');
  if (!username) {
    return null;
  }
  const user = findInvitedGuest(username, lastName);
  return user || {
    name: username,
    lastName: lastName,
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    isUnrecognizedUser: true,
  };
};