const invitedGuests = [
  {
    name:'Haley',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'stickz',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Teresa',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pumpkin',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Ralph',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pumpkin',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Hunter',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pranksonmom',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Hailey',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'pranksonmom',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Erwin',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'thelegend',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Sharon',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'hummingbird',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Alex',
    isFamily: false,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'sneeze!where?',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Garrison',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: true,
    password: 'haleydoesntknow',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Anne',
    isFamily: true,
    isWeddingParty: false,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'sassycooper',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Gary',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'sassycooper',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Barb',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Barbara',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Danny',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Daniel',
    isFamily: true,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    password: 'rootbeer',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Katelyn',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: false,
    isFlying: false,
    password: 'bananaslug',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Meggie',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'chomo',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Meaghan',
    isFamily: true,
    isWeddingParty: true,
    isBridesmaid: true,
    isDriving: true,
    isFlying: false,
    password: 'chomo',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Justin',
    isFamily: false,
    isWeddingParty: true,
    isDriving: true,
    isFlying: false,
    password: 'beanbagflute',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Mallory',
    isFamily: false,
    isWeddingParty: true,
    isDriving: true,
    isFlying: false,
    password: 'beanbagflute',
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Monic',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Joel',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Katy',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Jamie',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Kevin',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Courtney',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Cory',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Lydia',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Emma',
    isFamily: false,
    isWeddingParty: false,
    isDriving: false,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Israel',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Sandra',
    lastName: 'Davila',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Garrett',
    isFamily: false,
    isWeddingParty: false,
    isDriving: false,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Susanna',
    isFamily: false,
    isWeddingParty: false,
    isDriving: false,
    isFlying: true,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Nicole',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
  {
    name:'Leif',
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: false,
    rsvpDate: 'November 1, 2023',
  },
];

export function findInvitedGuest(name) {
  return invitedGuests.find((guest) => guest.name.toLowerCase() === name.toLowerCase());
}

export function storeUser(name) {
  const user = findInvitedGuest(name) || {
    name,
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    isUnrecognisedUser: true,
  };
  localStorage.setItem('user', user.name);
  return user;
}

export function removeUser() {
  localStorage.removeItem('user');
}

export default function useUser() {
  const username = localStorage.getItem('user');
  if (!username) {
    return null;
  }
  const user = findInvitedGuest(username);
  return user || {
    name: username,
    isFamily: false,
    isWeddingParty: false,
    isDriving: true,
    isFlying: true,
    isUnrecognisedUser: true,
  };
};